# 自動適用される synonym -> canonical マップ。TAGS.md が単一情報源。
# 値は必ず CANONICAL のいずれか。_alltags.txt の 628 タグすべてをキーに含む。

CANONICAL = {
    # プロトコル・トランスポート
    "bgp", "dns", "tcp-udp", "tls", "ipsec", "http", "mtu", "icmp",
    # アドレッシング
    "cidr", "subnetting", "ipv6", "ip-exhaustion", "nat", "public-ip",
    # 経路制御
    "route-table", "longest-prefix", "blackhole", "route-propagation", "ecmp",
    # 接続・ハイブリッド
    "vpc-peering", "transit-gateway", "direct-connect", "vpn", "client-vpn",
    "privatelink", "vpc-endpoint", "vpc-sharing", "hybrid",
    # ロードバランシング
    "alb", "nlb", "gwlb", "cross-zone", "health-check", "target-type", "proxy-protocol",
    # DNSルーティング
    "routing-policy", "failover",
    # セキュリティ
    "security-group", "nacl", "stateful-stateless", "waf", "shield",
    "network-firewall", "firewall-manager", "encryption", "iam-policy", "scp",
    "least-privilege", "source-condition",
    # 監視・運用
    "flow-logs", "monitoring", "reachability-analyzer", "traffic-mirroring",
    "cloudtrail-events", "config-rules", "troubleshooting",
    # コンピュート/コンテナのネットワーキング
    "eni", "enhanced-networking", "placement-group", "awsvpc",
    "service-discovery", "service-mesh",
    # コンテンツ配信・APIエッジ
    "edge-caching", "oac", "global-accelerator", "api-endpoint", "vpc-link",
    # アプリ統合
    "pub-sub", "message-queue", "event-routing",
    # ガバナンス・コスト・運用管理
    "cost", "data-transfer", "multi-account", "landing-zone", "iac", "quotas",
    "well-architected", "auto-scaling", "console-security", "automation",
    # 設計属性
    "multi-az", "multi-region", "high-availability", "use-case-fit",
}

TAG_MAP = {
    # ---- canonical self-maps（78語） ----
    "bgp": "bgp",
    "dns": "dns",
    "tcp-udp": "tcp-udp",
    "tls": "tls",
    "ipsec": "ipsec",
    "http": "http",
    "mtu": "mtu",
    "icmp": "icmp",
    "cidr": "cidr",
    "subnetting": "subnetting",
    "ipv6": "ipv6",
    "ip-exhaustion": "ip-exhaustion",
    "nat": "nat",
    "public-ip": "public-ip",
    "route-table": "route-table",
    "longest-prefix": "longest-prefix",
    "blackhole": "blackhole",
    "route-propagation": "route-propagation",
    "ecmp": "ecmp",
    "vpc-peering": "vpc-peering",
    "transit-gateway": "transit-gateway",
    "direct-connect": "direct-connect",
    "vpn": "vpn",
    "client-vpn": "client-vpn",
    "privatelink": "privatelink",
    "vpc-endpoint": "vpc-endpoint",
    "vpc-sharing": "vpc-sharing",
    "hybrid": "hybrid",
    "alb": "alb",
    "nlb": "nlb",
    "gwlb": "gwlb",
    "cross-zone": "cross-zone",
    "health-check": "health-check",
    "target-type": "target-type",
    "proxy-protocol": "proxy-protocol",
    "routing-policy": "routing-policy",
    "failover": "failover",
    "security-group": "security-group",
    "nacl": "nacl",
    "stateful-stateless": "stateful-stateless",
    "waf": "waf",
    "shield": "shield",
    "network-firewall": "network-firewall",
    "firewall-manager": "firewall-manager",
    "encryption": "encryption",
    "iam-policy": "iam-policy",
    "scp": "scp",
    "least-privilege": "least-privilege",
    "source-condition": "source-condition",
    "flow-logs": "flow-logs",
    "monitoring": "monitoring",
    "reachability-analyzer": "reachability-analyzer",
    "traffic-mirroring": "traffic-mirroring",
    "cloudtrail-events": "cloudtrail-events",
    "config-rules": "config-rules",
    "troubleshooting": "troubleshooting",
    "eni": "eni",
    "enhanced-networking": "enhanced-networking",
    "placement-group": "placement-group",
    "awsvpc": "awsvpc",
    "service-discovery": "service-discovery",
    "service-mesh": "service-mesh",
    "edge-caching": "edge-caching",
    "oac": "oac",
    "global-accelerator": "global-accelerator",
    "api-endpoint": "api-endpoint",
    "vpc-link": "vpc-link",
    "pub-sub": "pub-sub",
    "message-queue": "message-queue",
    "event-routing": "event-routing",
    "cost": "cost",
    "data-transfer": "data-transfer",
    "multi-account": "multi-account",
    "landing-zone": "landing-zone",
    "iac": "iac",
    "quotas": "quotas",
    "well-architected": "well-architected",
    "auto-scaling": "auto-scaling",
    "console-security": "console-security",
    "automation": "automation",
    "multi-az": "multi-az",
    "multi-region": "multi-region",
    "high-availability": "high-availability",
    "use-case-fit": "use-case-fit",

    # ---- synonym -> canonical（628タグの残り） ----

    # RAM / 共有
    "ram": "vpc-sharing",
    "shareable-resources": "vpc-sharing",
    "shared-resources": "vpc-sharing",
    "sharing-targets": "vpc-sharing",
    "vpc-standardization": "vpc-sharing",

    # WAF / Shield / FMS
    "fms": "firewall-manager",
    "shield-advanced": "shield",
    "shield-standard": "shield",
    "managed-rule": "waf",
    "managed-rules": "waf",
    "rate-based": "waf",
    "protected-resources": "firewall-manager",
    "network-protection": "shield",
    "flood": "shield",
    "cost-protection": "shield",
    "policy-types": "firewall-manager",

    # コスト
    "pricing": "cost",
    "cost-explorer": "cost",
    "cost-optimization": "cost",
    "optimization": "cost",
    "usage-type": "cost",
    "cur": "cost",
    "idle-resources": "cost",
    "nat-cost": "cost",
    "trusted-advisor": "cost",
    "anomaly-detection": "cost",

    # データ転送
    "data-events": "cloudtrail-events",
    "az-transfer": "data-transfer",
    "region-transfer": "data-transfer",
    "cross-region-replication": "data-transfer",
    "cross-az": "data-transfer",
    "egress": "data-transfer",
    "centralized-egress": "data-transfer",

    # ヘルスチェック / LB
    "health-check-type": "health-check",
    "healthy-instances": "health-check",
    "elb-health-check": "health-check",
    "health-api": "health-check",
    "nat-gateway": "nat",
    "snat": "nat",
    "nlb-nat": "nat",
    "elb": "alb",
    "elb-alignment": "alb",
    "elb-logs": "alb",
    "load-balancer-controller": "alb",
    "load-balancer": "alb",
    "lb-selection": "use-case-fit",
    "layer4": "nlb",
    "l3-l4": "nlb",
    "l7": "alb",
    "l7-routing": "alb",
    "target-group": "target-type",
    "target-mode": "target-type",
    "ip-target": "target-type",
    "ip-mode": "target-type",
    "instance": "target-type",
    "nlb-alb": "use-case-fit",
    "nlb-gwlb": "use-case-fit",
    "geneve": "gwlb",
    "gwlbe": "gwlb",
    "static-ip": "nlb",
    "client-ip": "proxy-protocol",
    "passthrough": "nlb",
    "symmetric-flow": "gwlb",
    "single-flow": "gwlb",
    "appliance-mode": "transit-gateway",

    # ENI / コンテナネット
    "hyperplane-eni": "eni",
    "branch-eni": "eni",
    "trunk-eni": "eni",
    "task-eni": "eni",
    "eni-trunking": "eni",
    "network-interface": "eni",
    "multiple-eni": "eni",
    "nhi": "eni",
    "pod-ip": "eni",
    "security-groups-for-pods": "eni",
    "eip": "public-ip",
    "ip-efficiency": "ip-exhaustion",
    "ip-overlap": "ip-exhaustion",
    "overlapping-cidr": "ip-exhaustion",
    "ip-overlap-resolution": "ip-exhaustion",
    "subnet-ip-exhaustion": "ip-exhaustion",
    "max-pods": "awsvpc",
    "vpc-cni": "awsvpc",
    "network-mode": "awsvpc",
    "bridge": "awsvpc",
    "host": "awsvpc",
    "custom-networking": "awsvpc",
    "assign-public-ip": "awsvpc",
    "platform-version": "awsvpc",
    "prefix-delegation": "awsvpc",

    # private-dns / privatelink / endpoint
    "private-dns": "vpc-endpoint",
    "privatelink-self": "privatelink",
    "endpoint-policy": "vpc-endpoint",
    "gateway-endpoint": "vpc-endpoint",
    "gateway-vs-interface": "vpc-endpoint",
    "gateway-vs-interface-endpoint": "vpc-endpoint",
    "interface-endpoint": "vpc-endpoint",
    "s3-gateway": "vpc-endpoint",
    "endpoint-type": "vpc-endpoint",
    "endpoint-types": "vpc-endpoint",
    "endpoint-format": "vpc-endpoint",
    "endpoint-service": "privatelink",
    "consumer-permissions": "privatelink",
    "vpce": "vpc-endpoint",
    "source-vpce": "source-condition",
    "source-vpc": "source-condition",
    "source-ip": "source-condition",

    # TGW
    "tgw": "transit-gateway",
    "vgw-vs-tgw": "transit-gateway",
    "vs-peering-tgw": "transit-gateway",
    "association": "transit-gateway",
    "association-vs-propagation": "route-propagation",
    "attachment-types": "transit-gateway",
    "branch-to-branch": "transit-gateway",
    "transitive": "transit-gateway",
    "inspection-vpc": "network-firewall",
    "multi-vpc": "transit-gateway",
    "centralized": "transit-gateway",

    # セキュリティ
    "security": "security-group",
    "outbound": "security-group",
    "inbound": "security-group",
    "bucket-policy": "iam-policy",
    "topic-policy": "iam-policy",
    "resource-policy": "iam-policy",
    "access-policy": "iam-policy",
    "sg-policy": "security-group",
    "security-group-vs-nacl": "stateful-stateless",
    "stateful": "network-firewall",
    "stateless": "network-firewall",
    "stateful-actions": "network-firewall",
    "suricata": "network-firewall",
    "domain-filtering": "network-firewall",
    "inspection": "network-firewall",
    "dns-firewall": "network-firewall",
    "firewall-subnet": "network-firewall",
    "forward-to-stateful": "network-firewall",
    "full-checks": "network-firewall",
    "default-allow": "nacl",
    "rule-evaluation": "network-firewall",
    "default-behavior": "stateful-stateless",
    "default-destination": "network-firewall",
    "network-restriction": "security-group",
    "network-zone": "security-group",
    "segmentation": "security-group",
    "defense-in-depth": "security-group",
    "layer-separation": "security-group",
    "layers": "security-group",
    "network-layering": "security-group",
    "iam": "iam-policy",
    "iam-role": "iam-policy",
    "role": "iam-policy",
    "tool-role": "iam-policy",
    "access-control": "iam-policy",
    "authentication": "iam-policy",
    "authorization": "iam-policy",
    "principal": "iam-policy",
    "principals": "iam-policy",
    "condition-keys": "source-condition",
    "credentials": "iam-policy",
    "permissions": "iam-policy",
    "session": "iam-policy",
    "policy": "iam-policy",
    "region-restriction": "source-condition",
    "encryption-in-transit": "encryption",
    "secure-transport": "encryption",
    "sse-kms": "encryption",
    "field-level-encryption": "encryption",
    "macsec": "encryption",
    "pii": "encryption",
    "data-leak": "encryption",
    "data-protection": "encryption",
    "guardduty": "monitoring",
    "detective": "monitoring",
    "realtime-detection": "monitoring",
    "security-alert": "monitoring",

    # ACM / TLS
    "acm": "tls",
    "certificates": "tls",
    "server-certificate": "tls",
    "https": "tls",
    "sni": "tls",
    "mutual-cert": "client-vpn",

    # CloudTrail / Config
    "cloudtrail": "cloudtrail-events",
    "cloudtrail-vs-flowlogs": "cloudtrail-events",
    "config-vs-cloudtrail": "cloudtrail-events",
    "config": "config-rules",
    "conformance-pack": "config-rules",
    "configuration-item": "config-rules",
    "recorded-resources": "config-rules",
    "aggregator": "config-rules",
    "config-dependency": "config-rules",
    "advanced-event-selectors": "cloudtrail-events",
    "management-events": "cloudtrail-events",
    "event-history": "cloudtrail-events",
    "event-source": "cloudtrail-events",
    "event-types": "cloudtrail-events",
    "event-selectors": "cloudtrail-events",
    "network-activity-events": "cloudtrail-events",
    "network-activity": "cloudtrail-events",
    "network-events": "cloudtrail-events",
    "account-events": "cloudtrail-events",
    "aws-events": "cloudtrail-events",
    "organization-trail": "cloudtrail-events",
    "multi-region-trail": "cloudtrail-events",
    "audit": "cloudtrail-events",
    "compliance": "config-rules",
    "controls": "config-rules",
    "baseline": "config-rules",
    "network-change-tracking": "config-rules",
    "network-tracking": "config-rules",

    # CloudWatch / 監視
    "cloudwatch": "monitoring",
    "cloudwatch-agent": "monitoring",
    "cloudwatch-alarm": "monitoring",
    "cloudwatch-logs": "monitoring",
    "alarm": "monitoring",
    "metrics": "monitoring",
    "custom-metrics": "monitoring",
    "metric-filter": "monitoring",
    "detailed-monitoring": "monitoring",
    "dashboard-types": "monitoring",
    "logging": "monitoring",
    "logs-insights": "monitoring",
    "log-destination": "monitoring",
    "retention": "monitoring",
    "observability": "monitoring",
    "network-monitoring": "monitoring",
    "network-flow-monitor": "monitoring",
    "network-health-indicator": "monitoring",
    "network-synthetic-monitor": "monitoring",
    "internet-monitor": "monitoring",
    "network-manager": "monitoring",
    "network-operations": "monitoring",
    "network-features": "monitoring",
    "canary": "monitoring",
    "synthetic": "monitoring",
    "thresholds": "monitoring",
    "anomaly": "monitoring",
    "athena": "monitoring",
    "real-time-logs": "monitoring",
    "visualization-tools": "monitoring",
    "x-ray": "monitoring",
    "internet": "monitoring",
    "internet-access": "nat",

    # Flow Logs
    "vpc-flow-logs": "flow-logs",
    "flow-logs-analysis": "flow-logs",

    # Reachability / 経路解析
    "route-analyzer": "reachability-analyzer",

    # トラブルシュート
    "troubleshoot": "troubleshooting",
    "root-cause": "troubleshooting",
    "application-failure": "troubleshooting",
    "instance-replacement": "troubleshooting",
    "port-conflict": "troubleshooting",
    "recovery": "high-availability",

    # ルート / 経路
    "route": "route-table",
    "route-tables": "route-table",
    "routing": "route-table",
    "routing-constraint": "route-table",
    "route-evaluation": "longest-prefix",
    "more-specific": "bgp",
    "static-routes": "route-table",
    "static-vs-dynamic": "route-table",
    "router": "route-table",
    "scope-boundary": "route-table",
    "scope": "route-table",
    "scoping": "route-table",

    # BGP 細分
    "local-pref": "bgp",
    "as-path-prepend": "bgp",
    "path-selection": "bgp",
    "route-advertisement": "bgp",
    "asn": "bgp",
    "gre-bgp": "bgp",
    "split-horizon": "bgp",

    # MTU 細分
    "jumbo-frames": "mtu",
    "jumbo": "mtu",
    "mss-clamping": "mtu",
    "pmtud": "mtu",

    # Direct Connect / VIF
    "direct-connect-self": "direct-connect",
    "directconnect": "direct-connect",
    "dxgw": "direct-connect",
    "dx-backup": "direct-connect",
    "dx-vpn": "hybrid",
    "public-vif": "direct-connect",
    "private-vif": "direct-connect",
    "transit-vif": "direct-connect",
    "vif": "direct-connect",
    "vif-count": "direct-connect",
    "dedicated-vs-hosted": "direct-connect",
    "dedicated": "direct-connect",
    "sitelink": "direct-connect",
    "maximum-resiliency": "direct-connect",
    "high-resiliency": "direct-connect",
    "redundancy": "high-availability",

    # VPN
    "accelerated-vpn": "vpn",
    "accelerated": "vpn",
    "vpn-backup": "vpn",
    "private-ip-vpn": "vpn",
    "tunnels": "vpn",
    "cloudhub": "vpn",
    "sd-wan": "vpn",
    "vgw": "vpn",
    "virtual-gateway": "vpn",
    "igw": "public-ip",
    "multi-site": "hybrid",
    "on-premises": "hybrid",
    "connectivity": "hybrid",
    "connections": "hybrid",
    "connect": "transit-gateway",

    # Client VPN
    "split-tunnel": "client-vpn",
    "full-tunnel": "client-vpn",
    "saml": "client-vpn",
    "authorization-rule": "client-vpn",
    "client-cidr": "client-vpn",
    "client-vpn-vs-s2s": "client-vpn",
    "remote-access": "client-vpn",

    # Peering
    "peering": "vpc-peering",
    "vs-peering": "vpc-peering",

    # DNS / Route 53
    "route53": "routing-policy",
    "route-53": "routing-policy",
    "vs-route53": "routing-policy",
    "weighted": "routing-policy",
    "weighted-routing": "routing-policy",
    "latency": "routing-policy",
    "geolocation": "routing-policy",
    "geoproximity": "routing-policy",
    "multivalue": "routing-policy",
    "endpoint-weight": "routing-policy",
    "active-active": "routing-policy",
    "active-passive": "failover",
    "alias": "routing-policy",
    "cname": "dns",
    "zone-apex": "dns",
    "dns-record-types": "dns",
    "dns-ttl": "dns",
    "dns-settings": "dns",
    "name-resolution": "dns",
    "public-dns": "dns",
    "resolver": "dns",
    "resolver-rules": "dns",
    "vpc-resolver": "dns",
    "hybrid-dns": "dns",
    "phz": "dns",
    "route53-private-hosted-zone": "dns",
    "srv": "service-discovery",
    "query": "dns",
    "arc": "high-availability",

    # エッジ / CloudFront
    "cloudfront": "edge-caching",
    "cloudfront-functions": "edge-caching",
    "lambda-edge": "edge-caching",
    "edge-functions": "edge-caching",
    "edge-optimized": "edge-caching",
    "caching": "edge-caching",
    "origin-groups": "edge-caching",
    "origin-protection": "edge-caching",
    "private-content": "edge-caching",
    "signed-cookie": "edge-caching",
    "signed-url": "edge-caching",
    "vpc-origin": "edge-caching",
    "vs-cloudfront": "use-case-fit",
    "cloudfront-vs-global-accelerator": "use-case-fit",
    "oai": "oac",

    # Global Accelerator
    "anycast-ip": "global-accelerator",
    "traffic-dial": "global-accelerator",
    "client-affinity": "global-accelerator",
    "standard-vs-custom-routing": "global-accelerator",

    # API / エンドポイント
    "api": "api-endpoint",
    "api-gateway": "api-endpoint",
    "http-api": "api-endpoint",
    "rest-api": "api-endpoint",
    "websocket-api": "api-endpoint",
    "http-methods": "api-endpoint",
    "private-api": "api-endpoint",
    "custom-domain": "api-endpoint",
    "backend-integration": "api-endpoint",
    "private-backend": "api-endpoint",
    "throttling": "api-endpoint",
    "429": "api-endpoint",
    "vpc-lattice": "vpc-link",
    "vpc-link-self": "vpc-link",

    # アプリ統合
    "sns": "pub-sub",
    "topic": "pub-sub",
    "subscription": "pub-sub",
    "fanout": "pub-sub",
    "fanout-target": "pub-sub",
    "notification": "pub-sub",
    "delivery-reliability": "pub-sub",
    "sqs": "message-queue",
    "queue-type": "message-queue",
    "fifo": "message-queue",
    "dlq": "message-queue",
    "visibility-timeout": "message-queue",
    "send-message": "message-queue",
    "ordering": "message-queue",
    "buffering": "message-queue",
    "decoupling": "message-queue",
    "retry": "message-queue",
    "eventbridge": "event-routing",
    "event-bus": "event-routing",
    "default-bus": "event-routing",
    "event-driven": "event-routing",
    "putevents": "event-routing",
    "pipes": "event-routing",
    "scheduler": "event-routing",
    "schedule": "event-routing",
    "rule": "event-routing",
    "distributed-systems": "event-routing",
    "distributed": "event-routing",
    "orchestration": "event-routing",

    # コンテナ / サービスディスカバリ / メッシュ
    "cloud-map": "service-discovery",
    "namespace": "service-discovery",
    "http-namespace": "service-discovery",
    "service-connect": "service-discovery",
    "ecs-service-connect": "service-discovery",
    "ecs-service-discovery": "service-discovery",
    "discoverinstances": "service-discovery",
    "registration": "service-discovery",
    "auto-registration": "service-discovery",
    "envoy": "service-mesh",
    "envoy-overhead": "service-mesh",
    "virtual-router": "service-mesh",
    "virtual-node": "service-mesh",
    "app-mesh": "service-mesh",
    "vpc-config": "awsvpc",
    "vpc-lambda": "eni",
    "vpc-workload": "awsvpc",

    # ECS / EKS / ECR / Fargate
    "ecs": "awsvpc",
    "eks": "awsvpc",
    "eks-on-fargate": "awsvpc",
    "fargate": "awsvpc",
    "ecr": "vpc-endpoint",
    "ecr-api": "vpc-endpoint",
    "ecr-dkr": "vpc-endpoint",
    "image-layer": "vpc-endpoint",
    "image-pull": "vpc-endpoint",
    "private-pull": "vpc-endpoint",
    "private-registry": "vpc-endpoint",
    "private-publish": "vpc-endpoint",

    # 拡張ネットワーキング
    "ena": "enhanced-networking",
    "efa": "enhanced-networking",
    "bandwidth": "enhanced-networking",
    "network-bandwidth": "enhanced-networking",
    "hpc": "enhanced-networking",
    "burst": "enhanced-networking",
    "density": "enhanced-networking",
    "capacity": "enhanced-networking",
    "performance": "enhanced-networking",

    # Placement Group
    "spread": "placement-group",
    "partition": "placement-group",
    "cluster": "placement-group",

    # Organizations / マルチアカウント
    "organizations": "multi-account",
    "organizations-integration": "multi-account",
    "delegated-admin": "multi-account",
    "admin-account": "multi-account",
    "management-account": "multi-account",
    "accounts": "multi-account",
    "cross-account": "multi-account",
    "cross-stack": "iac",
    "invitation": "multi-account",
    "acceptance": "multi-account",
    "ownership": "multi-account",
    "delegation": "multi-account",
    "global-resources": "multi-region",
    "global": "multi-region",

    # Landing Zone / ガバナンス
    "guardrails": "scp",
    "guardrail": "scp",
    "preventive": "scp",
    "account-factory": "landing-zone",
    "control-tower": "landing-zone",
    "governance": "landing-zone",
    "enablement": "landing-zone",
    "default": "landing-zone",
    "declarative": "iac",

    # IaC / CloudFormation
    "cloudformation": "iac",
    "template": "iac",
    "stack": "iac",
    "stack-sets": "iac",
    "drift": "iac",
    "drift-detection": "iac",
    "dependson": "iac",
    "dependency": "iac",
    "export-import": "iac",
    "no-redeploy": "iac",
    "auto-apply": "iac",
    "scheduled-change": "automation",
    "imperative-vs-declarative": "iac",
    "cli-vs-iac": "iac",
    "repeatability": "iac",
    "dry": "iac",

    # Quotas / Limits
    "service-limits": "quotas",
    "limits": "quotas",
    "scaling-limit": "quotas",
    "network-quotas": "quotas",
    "constraints": "quotas",
    "count": "quotas",
    "pagination": "quotas",

    # Well-Architected
    "pillars": "well-architected",
    "reliability": "well-architected",
    "resiliency": "well-architected",
    "framework": "well-architected",
    "design-principles": "well-architected",
    "best-practice": "well-architected",
    "fault-tolerance": "high-availability",
    "single-point-of-failure": "high-availability",
    "availability": "high-availability",
    "sla": "high-availability",
    "end-to-end": "well-architected",

    # Auto Scaling
    "scaling": "auto-scaling",
    "az-rebalance": "auto-scaling",
    "rebalance": "auto-scaling",
    "launch-template": "auto-scaling",
    "scaling-trigger": "auto-scaling",
    "concurrency": "auto-scaling",
    "cold-start": "auto-scaling",
    "add-az": "auto-scaling",

    # Console Security
    "console-access": "console-security",
    "console-api": "console-security",
    "console-use-cases": "console-security",
    "restricted-ssh": "console-security",
    "sso": "console-security",
    "active-directory": "console-security",

    # Automation
    "remediation": "automation",
    "auto-remediation": "automation",
    "ssm-automation": "automation",
    "automation-chain": "automation",
    "manual-change": "automation",
    "periodic": "automation",
    "describe": "automation",
    "jmespath": "automation",
    "sdk": "automation",
    "migration": "automation",

    # マルチAZ / リージョン
    "availability-zone": "multi-az",
    "regional": "multi-region",
    "region": "multi-region",
    "us-east-1": "multi-region",
    "standard": "use-case-fit",

    # CIDR / サブネット / IP
    "subnet": "subnetting",
    "subnet-alignment": "subnetting",
    "private-subnet": "subnetting",
    "public-subnet": "subnetting",
    "secondary-cidr": "cidr",
    "prefix-list": "route-table",
    "ip": "public-ip",
    "ipv4": "public-ip",
    "byoip": "public-ip",
    "dedicated-ip": "public-ip",
    "static-ip-allocation": "public-ip",
    "instance-id": "eni",
    "instance-type": "enhanced-networking",
    "port": "tcp-udp",
    "dynamic-port": "tcp-udp",
    "layer4-port": "tcp-udp",
    "overlay": "transit-gateway",

    # VPC 基本
    "vpc": "subnetting",
    "ingress": "security-group",

    # その他サービス
    "s3": "vpc-endpoint",
    "lambda": "eni",
    "dynamodb": "vpc-endpoint",
    "rds-access": "vpc-endpoint",
    "private-access": "vpc-endpoint",
    "private-resource": "vpc-endpoint",
    "private-content-access": "edge-caching",

    # ガバナンス・運用の汎用
    "support-plan": "cost",
    "consumer": "privatelink",

    # 汎用すぎる語 -> use-case-fit
    "use-case": "use-case-fit",
    "comparison": "use-case-fit",
    "design": "use-case-fit",
    "core-concept": "use-case-fit",
    "gotcha": "use-case-fit",
    "pitfall": "use-case-fit",
    "characteristics": "use-case-fit",
    "selection": "use-case-fit",
    "decision": "use-case-fit",
    "types": "use-case-fit",
    "complement": "use-case-fit",
    "integration": "use-case-fit",
    "design-pattern": "use-case-fit",
    "typical-patterns": "use-case-fit",
    "equivalence": "use-case-fit",
    "evaluation": "use-case-fit",
    "requirements": "use-case-fit",
    "prerequisite": "use-case-fit",
    "prerequisites": "use-case-fit",
    "deprecation": "use-case-fit",
    "legacy": "use-case-fit",
    "custom": "use-case-fit",
    "separation": "use-case-fit",
    "transparent": "use-case-fit",
    "regional-vs-edge": "use-case-fit",
    "data-freshness": "use-case-fit",
    "timeline": "use-case-fit",
    "end-user": "use-case-fit",
    "srt": "use-case-fit",
    "wcu": "quotas",

    # 監視・運用の細分（残り）
    "network-change": "config-rules",

    # ロードバランサ補足
    "target": "target-type",
}
