basic_auth_username: ENC[AES256_GCM,data:eroWFhMRMliH,iv:CVzmlfdMcRWSnVp3/U9qyzBYlMAuR8bvMPHAaTEqsZM=,tag:Oz1D6enw+RH2h+rr9srOnw==,type:str]
basic_auth_password: ENC[AES256_GCM,data:6xQ4mBeuOQah1EJoXm+cg866xwE=,iv:LK+LnEfVW960qbtPq5ZYamkTXs7DS8BrftIXDBSnc/E=,tag:FxZ5lgq8dibkXQ9XQ8vdOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWejBHV1BJSUh5eXA0SVRM
            SkhjOHk3Y2Q2YnBWM1JOd0dtRi85S2hOK2hFCjFHZ0R1Q0p5Q3BEa0lWNmI2MUdL
            RzAvbnR6aEVDaTB0cUxBS3VXMjNXN00KLS0tIG1LcFZSYVQ1cWE3TkMxY3VMSFBz
            V0QzQXFNaWljUU9TWEF6b1hlRWpLOHcKV949DEegiXM2spq3/l2GuQArfnFHM4n4
            3ZJXECNHwvsZ49Sbtp+AAVbfl9seFWFIkm0xK5sFvD7aaDYjkXKSjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qyr4xznv0exnxacqlyy6x4wz8c7yhdw5h5gj7rmqf0wms55agfrszhgveq
    encrypted_regex: ^(basic_auth_username|basic_auth_password)$
    lastmodified: "2026-06-13T12:19:49Z"
    mac: ENC[AES256_GCM,data:3FotBqGmG7qy6Dh4LkYWf/UozvjvDu4PDdov4+iiBCibpRMXKj/I45zUPkBW7kq2AIsUEs9xjnNC9oJk8oWmOJJbe2KSizCWUKWu6bdMX8TMnK4l7Mw2AP0dHiGn1IFDk3RFmxoEthmR95pqeQ2EvMPvH3WT3PO95jJ0rWY5cmY=,iv:T8sEREWXW4G453na/Fc0YmO3aLr/u9HWKk1FhP1INos=,tag:GyL2TAEEMKnv9ArUHtQwcg==,type:str]
    version: 3.13.1
